/**
 * Tournament App API
 * Rest API using OpenAPI 3 for a tutorial Tournament application
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FinalPhaseMatchScoresDTO { 
    comment?: string;
}